# Generated by Django 4.0.4 on 2022-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=570)),
                ('message', models.TextField(max_length=570)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
